# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: server npm i
      run: npm i
    - name: cd client & npm i
      run: |
        cd /home/tyler/actions-runner/_work/website-fullstack/website-fullstack/client
        npm i
    - name: cd client & npm run build
      run: |
        cd /home/tyler/actions-runner/_work/website-fullstack/website-fullstack/client
        npm run build
    - name: stop nginx
      run: sudo service nginx stop
    - name: rm /var/www/html, mv build & grep
      run: |
        sudo rm -rf /var/www/html
        cd /home/tyler/actions-runner/_work/website-fullstack/website-fullstack/client
        sudo mv build /var/www/html
        sudo grep -rl localhost /var/www/html | xargs sed -i 's/http:\/\/localhost:8000//g'
    - name: copy .env from ~ into server
      run: cp ~/.env /home/tyler/actions-runner/_work/website-fullstack/website-fullstack/.env
    - name: restart pm2 & nginx
      run: |
        cd /home/tyler/actions-runner/_work/website-fullstack/website-fullstack
        pm2 restart all
        sudo service nginx restart
