# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: |
        cd ~/action-runner/website-fullstack/website-fullstack/website-fullstack/client
        npm i
    - run: |
        cd ~/action-runner/website-fullstack/website-fullstack/website-fullstack/client
        npm run build
    - run: |
        cd ~/action-runner/website-fullstack/website-fullstack/website-fullstack/client
        mv ~/action-runner/website-fullstack/website-fullstack/website-fullstack/client/build /var/www/html
        grep -rl localhost ~/action-runner/website-fullstack/website-fullstack/website-fullstack/client | xargs sed -i 's/http:\/\/localhost:8000//g'
    - run: cp ~/.env ~/action-runner/website-fullstack/website-fullstack/website-fullstack/server/.env
    - run: pm2 restart all
    - run: sudo service nginx restart
